### ISSUE TITLE
Does not seem to handle nested submodules that well.

### ISSUE THREAD

**Issue by espenakker** [wolfsilver/git-submodule-sort#1]
I have a repo that contains a "libraries" submodule. This "libraries" submodule contains a set of submodules pointing to library repos. This extension does a great job but it seems to just miss this one improvement to go all the way.

```
Repo
┗Libraries
┗━Library
```

or maybe

```
Repo
┗Libraries
 ┗Library
```

**Comment by wolfsilver** [comment]
This is an known issue. And I don't have an elegant way to solve.
It will take some time to solve this problem.
